### ISSUE TITLE
[FEATURE] Implement  `--group dev` instead of --dev (being deprecated)

### ISSUE THREAD

**Issue by toaster-code** [zeshuaro/vscode-poetry#138]
### What kind of feature are you missing?

Hello,
First of all thank you for the plugin.
I would like to suggest you to implement "--group dev" instead of "-dev", as seem in the warnings issued from poetry 1.2.0:

`poetry add --dev autopep8
The --dev option is deprecated, use the `--group dev` notation instead.
`

**Comment by zeshuaro** [comment]
That's great to know, I have been waiting for that feature to be released in stable versions on Poetry for a while. Thanks for sharing this, will also update the plugin to support this.
