### ISSUE TITLE
[BUG] no indication that commands are running when no terminal is open

### ISSUE THREAD

**Issue by DetachHead** [zeshuaro/vscode-poetry#782]
### Steps to Reproduce

1. close all terminal windows
2. run a command (eg. `Poetry: Update all packages`)

### Expected behaviour

either a terminal opens with the `poetry update` command being run, or some visual indication that there's a task running

### Actual behaviour

nothing appears to happen. however when opening a new terminal manually, the terminal created by the task will be visible

**Comment by zeshuaro** [comment]
Thanks for reporting this, VS Code probably changed this behaviour at some point and I didn't notice it. I've put up a PR to fix this and will be included in the next release.
